### ISSUE TITLE
tsr-detect-non-literal-fs-filename: TypeError when Linted Function Name Exists on Object.prototype

### ISSUE THREAD

**Issue by paulroper** [webschik/tslint-config-security#1]
Hey! Thanks for making this set of rules, we're finding them really useful to have on our project.

We've run in to a tiny bug with the `tsr-detect-non-literal-fs-filename` rule when it runs on a `toString` call. 

As `toString` exists as a function on the prototype of the `fsModuleMethodsArgumentsInfo` object, the rule thinks that it's found a match for `fs` and throws a `TypeError: fsArgsInfo.filter is not a function` error when it tries to lint it.

I guess more broadly this would affect any case where the name of the function being linted is a function on `Object.prototype`.

## Code Reference

When `methodName` is `toString`, this returns the object's `toString` function rather than an entry from the `fsModuleMethodsArgumentsInfo` list:

https://github.com/webschik/tslint-config-security/blob/master/src/rules/tsrDetectNonLiteralFsFilenameRule.ts#L16

And then this tries to call `filter` on the object's `toString` function:

https://github.com/webschik/tslint-config-security/blob/master/src/rules/tsrDetectNonLiteralFsFilenameRule.ts#L20

**Comment by webschik** [comment]
Hi @paulroper !
Thanks for the report, this issue is fixed in v1.2.0

**Comment by paulroper** [comment]
Amazing! We've just updated and the error has gone away, thank you 🎉
