### ISSUE TITLE
Commit c5e22f78e9c5a3b70c88e20d1f5600b0c290ea01 moves typescript to devDependency but it's used as a dependency

### ISSUE THREAD

**Issue by SanderDeWaal1992** [webschik/tslint-config-security#11]
Commit c5e22f78e9c5a3b70c88e20d1f5600b0c290ea01 moves typescript to devDependency but it's used as a dependency.

Our builds do fail because our (non-standard) build system does depend on the dependency lists of modules to be correct. This issue is related to https://github.com/webschik/tslint-config-security/issues/9, I checked that our build system will work again when typescript is set as a dependency/peerDependency again.

**Comment by webschik** [comment]
@SanderDeWaal1992 , thanks!
I will add `typescript` to `peerDependencies`. For now, please, install typescript manually
