### ISSUE TITLE
Question: Is disabling linter rules for one file or a line of code possible?

### ISSUE THREAD

**Issue by bcko** [webschik/tslint-config-security#12]
Instead of disabling some linter rules globally, is disabling linter rules for one file or a line of code possible? Thank you.

**Comment by webschik** [comment]
Hi,

It's possible using the standard TSLint comment flags https://palantir.github.io/tslint/usage/rule-flags/
E.g.

```js
/* tslint:disable:tsr-detect-non-literal-fs-filename */
...
YOUR CODE
...
/* tslint:enable */
...
// tslint:disable-next-line:tsr-detect-non-literal-fs-filename
YOUR CODE
```
