### ISSUE TITLE
What is the future of the plugin?

### ISSUE THREAD

**Issue by MVrachev** [webschik/tslint-config-security#16]
I just read that issue [Roadmap TSlint -> ESlint](https://github.com/palantir/tslint/issues/4534) in which one of the maintainers of TSlint explains that TSlint will be deprecated and ESlint will scan TypeScript files in future.
 
As the maintainer points out this will require a lot of work but eventually will happen. 

There is also a statement by the ESlint community:
https://eslint.org/blog/2019/01/future-typescript-eslint#the-future-of-typescript-on-eslint 

What do you plan to do then with your project TSlint – config – security?

**Comment by webschik** [comment]
Hi @MVrachev ,

I think it's a good initiative of the TSLint team. I keep an eye on [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint) project and try to participate in its development.
I think TSLint team will support this project together with the ESLint team. 

When ESLint will be able to replace fully TSLint I'm going to adapt this module for ESLint or merge it with [eslint-plugin-security](https://github.com/nodesecurity/eslint-plugin-security) (but this module  looks unsupportable now)

**Comment by MVrachev** [comment]
Hi, TSLint is officially deprecated:
https://github.com/palantir/tslint/issues/3808#issuecomment-517933492
have you looked at how to change this plugin to work with ESlint?

**Comment by webschik** [comment]
Hi,
Definitely, I have plans to add ESLint support via [typescript-eslint/](https://github.com/typescript-eslint/typescript-eslint) plugin. Unfortunately, I have not much free time now, but I hope soon I'll will be able to start working on that.
