### ISSUE TITLE
[New feature] Add more info links to the output

### ISSUE THREAD

**Issue by MVrachev** [webschik/tslint-config-security#17]
It will be really useful to have "more info about the issue" field in the output.

Maybe you don't want to overwhelm the default human-readable output of TSLint but maybe you can add this into the JSON output?

I see that the JSON output provides a lot of information then more info information will be really cool.

You already have good documentation about every rule so it won't be hard to do.

PS: I have seen a few linters that do that - Bandit for Python is one example and I am helping with the Gosec for golang to do just that.

**Comment by webschik** [comment]
From v1.16.0 each rule contains  a property `metadata`, e.g. https://github.com/webschik/tslint-config-security/blob/master/src/rules/tsrDetectBufferNoassertRule.ts#L39

**Comment by MVrachev** [comment]
I don't see the "descriptionDetails" property or "description" property.
What I get in normal output is: 
![image](https://user-images.githubusercontent.com/16246778/56114604-0d8c9580-5f6a-11e9-9841-6aec3ad1cd1e.png)

I thought that I will have this in the JSON output but I don't:

```
[  
   {  
      "endPosition":{  
         "character":40,
         "line":11,
         "position":307
      },
      "failure":"eval with argument of type BinaryExpression",
      "name":"test/fixtures/typescript/vulnerable.js",
      "ruleName":"tsr-detect-eval-with-expression",
      "ruleSeverity":"ERROR",
      "startPosition":{  
         "character":9,
         "line":11,
         "position":276
      }
   },
   {  
      "endPosition":{  
         "character":11,
         "line":17,
         "position":465
      },
      "failure":"Found fs.open with non-literal argument at index 0",
      "name":"test/fixtures/typescript/vulnerable.js",
      "ruleName":"tsr-detect-non-literal-fs-filename",
      "ruleSeverity":"ERROR",
      "startPosition":{  
         "character":4,
         "line":17,
         "position":458
      }
   },
   {  
      "endPosition":{  
         "character":58,
         "line":5,
         "position":172
      },
      "failure":"Found possible SQL injection",
      "name":"test/fixtures/typescript/vulnerable.js",
      "ruleName":"tsr-detect-sql-literal-injection",
      "ruleSeverity":"ERROR",
      "startPosition":{  
         "character":16,
         "line":5,
         "position":130
      }
   }
]
```

Where do I access and see that data?

**Comment by webschik** [comment]
Hi @MVrachev ,

My mistake, `metadata` property is used only to generate documentation - https://palantir.github.io/tslint/develop/docs/

To the JSON output https://palantir.github.io/tslint/formatters/json/ I can pass only a `failure` string or the `fix` object (TSLint API)

**Comment by MVrachev** [comment]
So, that means that still, we can't access the "descriptionDetails" property from the command line?

One solution I think will be to pass "descriptionDetails" string into the failure string.

**Comment by webschik** [comment]
Yes
