### ISSUE TITLE
[New Feature] Confidence level for the issues

### ISSUE THREAD

**Issue by MVrachev** [webschik/tslint-config-security#19]
There are different issues - some are more concrete others are problems only in specific situations and easily can produce many false-positives. 

Like tsr-detect-non-literal-fs-filename rule is a problem when there is a user input which is not checked. This is a narrow case from all possible uses of fs.open/fs.read/fs.write and can easily produce many false-positives.

Having a confidence level will give an understanding of how possible is a false-positive from a concrete rule. 

Many static code analysis tools for security vulnerabilities like Bandit and Gosec are using "confidence" level in their output.

**Comment by MVrachev** [comment]
Is it possible to do that or TSLint doesn't provide us confidence level?

**Comment by webschik** [comment]
TSLint allows to configure a severity level (https://palantir.github.io/tslint/usage/configuration/), but currently, all rules from `tslint-config-security` have a severity **error**.

As a quick solution you may use
```js
// tslint:disable-next-line tsr-detect-non-literal-fs-filename
fs.open(myTrustedVariable)
```

**Comment by MVrachev** [comment]
When I say "confidence level" I mean how sure is the linter that what it gives you is a problem.
As an example in [Bandit](https://github.com/PyCQA/bandit) in a typical output you have: 

![image](https://user-images.githubusercontent.com/16246778/56293368-9b66ad00-6131-11e9-87fe-9ffa77b3525b.png)

**Comment by webschik** [comment]
TSLint doesn't provide API for that.
