### ISSUE TITLE
missing dependency on tslib and typescript in package json

### ISSUE THREAD

**Issue by SanderDeWaal1992** [webschik/tslint-config-security#2]
Our build is failing because tslib is not noted as dependency in package json.

Also TypeScript is noted as devdependency, even though it is present in a js file (src/rules/tsrDetectBufferNoassertRule.js). It should be set as dependency or it should not be present in the js file. It is probably in the js file because of line 64 of src/rules/tsrDetectBufferNoassertRule.ts.

**Comment by webschik** [comment]
Thanks, @SanderDeWaal1992! It's fixed in version 1.3.0
