### ISSUE TITLE
[bug] tsr-detect-non-literal-fs-filename false positives

### ISSUE THREAD

**Issue by victordidenko** [webschik/tslint-config-security#5]
```typescript
const s = 'test';
const o = {
  open(a: string) {},
};
o.open(s);
```
will trigger on the last line
> [tslint] Found fs.open with non-literal argument as index 0 (tsr-detect-non-literal-fs-filename)

I tried one, two and three arguments for method (I personally has `open` method with three arguments) – any of these cases triggers rule.

**Comment by webschik** [comment]
Fixed in **v1.5.0**, https://github.com/webschik/tslint-config-security#tsr-detect-non-literal-fs-filename
