### ISSUE TITLE
Typescript 3.x Support

### ISSUE THREAD

**Issue by g-marconet** [webschik/tslint-config-security#7]
Hi,

I noticed https://github.com/webschik/tslint-config-security/issues/4, but I am having issues getting the plugin to work with Typescript 3. The rules seem to be loaded just fine, but they never actually execute.

Steps to reproduce:
- Generate new project with `typescript` `3.0.3` and `tslint` `5.11.0`. Write a file that blatantly goes against one of the rules in `tslint-config-security`. Make sure `tslint.json` extends `tslint-config-security`.
- Clone `tslint-config-security` in an adjacent directory
- `npm install` in `tslint-config-security`
- `npm link` in `tslint-config-security`
- `npm link tslint-config-security` in your project
- Run `tslint`. Notice no errors are present (or at least, none from `tslint-config-security`)
- Go into the local clone of `tslint-config-security`, change the `typescript` version to `3.1.2`
- `npm install` in `tslint-config-security`
- Run `tslint`. Notice it now shows errors from `tslint-config-security`

This might also be an issue with `tslint` or with `typescript`. I haven't had an opportunity to dig much further into it.

**Comment by webschik** [comment]
I've updated Typescript and TSLint versions (see v1.8.0) and aligned them with `tslint-config-airbnb`
