### ISSUE TITLE
Commit c5e22f78e9c5a3b70c88e20d1f5600b0c290ea01 did remove dependency on tslib but it is still needed

### ISSUE THREAD

**Issue by SanderDeWaal1992** [webschik/tslint-config-security#9]
Commit c5e22f78e9c5a3b70c88e20d1f5600b0c290ea01 did remove dependency on tslib but it is still needed.

Our builds do fail because our (non-standard) build system does depend on the dependency lists of modules to be correct.

**Comment by webschik** [comment]
Please, install it manually with `npm i -D tslib`.
In the next version I will add `tslib` to `peerDependencies`

**Comment by SanderDeWaal1992** [comment]
Perfect, thank you.

**Comment by webschik** [comment]
done in v1.11.0
